# Generated by Django 4.1.7 on 2023-04-02 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome', models.CharField(max_length=150)),
                ('Brinde', models.CharField(max_length=150)),
                ('Sala', models.CharField(max_length=150)),
            ],
        ),
    ]
