# Generated by Django 4.1.7 on 2023-04-03 04:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='Data',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
