# Generated by Django 4.1.7 on 2023-04-03 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_meumodelo_remove_cliente_data'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MeuModelo',
        ),
    ]
