# Generated by Django 4.1.7 on 2023-04-04 15:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_delete_meumodelo'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='Tempo',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cliente',
            name='Sala',
            field=models.CharField(max_length=20),
        ),
    ]
