# Generated by Django 4.1.7 on 2023-04-04 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_cliente_tempo_alter_cliente_sala'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='Tempo',
            field=models.DateField(auto_now_add=True),
        ),
    ]
