# Generated by Django 4.1.7 on 2023-04-04 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_cliente_tempo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='Sala',
            field=models.CharField(choices=[('sala1', 'Sala 1'), ('sala2', 'Sala 2'), ('sala3', 'Sala 3'), ('sala4', 'Sala 4'), ('sala5', 'Sala 5'), ('sala6', 'Sala 6')], max_length=5),
        ),
    ]
