# Generated by Django 4.1.7 on 2023-04-04 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_cliente_sala'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='Sala',
            field=models.CharField(choices=[('GRAMADO - PEDRAS ALTAS', 'GRAMADO - PEDRAS ALTAS'), ('GRAMADO - STILO', 'GRAMADO - STILO'), ('GRAMADO - GOLDEN', 'GRAMADO - GOLDEN'), ('GRAMADO - NBA', 'GRAMADO - NBA'), ('CANELA - VIVERONE', 'CANELA - VIVERONE'), ('CANELA - CATEDRAL', 'CANELA - CATEDRAL'), ('BENTO GONÇALVES - VIVERONE', 'BENTO GONÇALVES - VIVERONE')], max_length=30),
        ),
    ]
