# Generated by Django 4.1.7 on 2023-04-05 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_cliente_sala'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='Brinde',
            field=models.CharField(choices=[('opcao1', 'Opção 1'), ('opcao2', 'Opção 2'), ('opcao3', 'Opção 3')], max_length=150),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='Sala',
            field=models.IntegerField(choices=[('GRAMADO - PEDRAS ALTAS', 'GRAMADO - PEDRAS ALTAS'), ('GRAMADO - STILO', 'GRAMADO - STILO'), ('GRAMADO - GOLDEN', 'GRAMADO - GOLDEN'), ('GRAMADO - NBA', 'GRAMADO - NBA'), ('CANELA - VIVERONE', 'CANELA - VIVERONE'), ('CANELA - CATEDRAL', 'CANELA - CATEDRAL'), ('BENTO GONÇALVES - VIVERONE', 'BENTO GONÇALVES - VIVERONE')]),
        ),
    ]
