# Generated by Django 4.1.7 on 2023-04-05 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_cliente_brinde_alter_cliente_sala'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='Nome',
            field=models.CharField(max_length=10),
        ),
    ]
