# Generated by Django 4.1.7 on 2023-04-05 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_cliente_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='Brinde',
            field=models.CharField(choices=[('opcao1', 'Opção 1'), ('opcao2', 'Opção 2'), ('opcao3', 'Opção 3'), ('GM - RESTAURANTE LAGHETTO', 'GM - RESTAURANTE LAGHETTO'), ('GM - FOTO NA NEVE', 'GM - FOTO NA NEVE'), ('GM - FUMACINHA', 'GM - FUMACINHA')], max_length=26),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='Nome',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='Sala',
            field=models.CharField(choices=[('GRAMADO - PEDRAS ALTAS', 'GRAMADO - PEDRAS ALTAS'), ('GRAMADO - STILO', 'GRAMADO - STILO'), ('GRAMADO - GOLDEN', 'GRAMADO - GOLDEN'), ('GRAMADO - NBA', 'GRAMADO - NBA'), ('CANELA - VIVERONE', 'CANELA - VIVERONE'), ('CANELA - CATEDRAL', 'CANELA - CATEDRAL'), ('BENTO GONÇALVES - VIVERONE', 'BENTO GONÇALVES - VIVERONE')], max_length=26),
        ),
    ]
