# Generated by Django 4.1.7 on 2023-04-14 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_cliente_brinde'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='Sala',
            field=models.CharField(choices=[('GRAMADO - PEDRAS ALTAS', 'GRAMADO - PEDRAS ALTAS'), ('GRAMADO - STILO', 'GRAMADO - STILO'), ('GRAMADO - GOLDEN', 'GRAMADO - GOLDEN'), ('GRAMADO - NBA', 'GRAMADO - NBA'), ('CANELA - VIVERONE', 'CANELA - VIVERONE'), ('CANELA - CATEDRAL', 'CANELA - CATEDRAL'), ('GRAMADO - SIENA', 'GRAMADO - SIENA'), ('BENTO GONÇALVES - VIVERONE', 'BENTO GONÇALVES - VIVERONE')], max_length=150),
        ),
    ]
