# Generated by Django 4.2 on 2023-04-16 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_cliente_sala'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='Sala',
            field=models.CharField(choices=[('GRAMADO - GOLDEN', 'GRAMADO - GOLDEN'), ('CANELA - VIVERONE', 'CANELA - VIVERONE'), ('GRAMADO - SIENA', 'GRAMADO - SIENA'), ('BENTO GONÇALVES - VIVERONE', 'BENTO GONÇALVES - VIVERONE')], max_length=150),
        ),
    ]
