# Generated by Django 4.1.7 on 2023-04-12 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_profile_delete_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
