# Generated by Django 4.2 on 2023-04-19 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_alter_cliente_brinde_alter_cliente_sala'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='quantidade',
            field=models.IntegerField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], default=1),
        ),
    ]
